//用户数据
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE' //更新用户需要的信息

//公会星级
export const GUILD_CENTER_STAR_UPDATE= 'GUILD_CENTER_STAR_UPDATE' //更新公会星级首页信息
export const GUILD_CENTER_STAR_RULES= 'GUILD_CENTER_STAR_RULES' //更新规则页

//公会商店
export const GUILD_CENTER_SHOP_UPDATE= 'GUILD_CENTER_SHOP_UPDATE' //更新公会商店首页信息
export const GUILD_CENTER_SHOP_SEARCH_LIST= 'GUILD_CENTER_SHOP_SEARCH_LIST' //更新公会商店搜索列表信息
export const GUILD_CENTER_SHOP_MORE_LIST= 'GUILD_CENTER_SHOP_MORE_LIST' //更新游戏公会商店商品列表
export const GUILD_CENTER_SHOP_GID_LIST= 'GUILD_CENTER_SHOP_GID_LIST' //更新该款游戏下公会商店商品列表
export const GUILD_CENTER_SHOP_INFO= 'GUILD_CENTER_SHOP_INFO' //更新商品详情页
export const GUILD_CENTER_SHOP_RECORD = 'GUILD_CENTER_SHOP_RECORD' //更新商品的领取记录
export const GUILD_CENTER_SHOP_RECORD_INFO = 'GUILD_CENTER_SHOP_RECORD_INFO'

//公会商店 星级礼包等传参数据结构
export const GUILD_CHANGE_CURRENT_GIFT= 'GUILD_CHANGE_CURRENT_GIFT' //更新即将访问的礼包id,用于详情页参数传递
export const GUILD_CHANGE_CURRENT_GAME= 'GUILD_CHANGE_CURRENT_GAME' //更新即将访问的游戏id,用于详情页参数传递
export const GUILD_CHANGE_CURRENT_PARTERMTER = 'GUILD_CHANGE_CURRENT_PARTERMTER' //更新参数
export const GUILD_CHANGE_CURRENT_KEYWORDS= 'GUILD_CHANGE_CURRENT_KEYWORDS' //更新即将访问的关键词,用于搜索页列表
export const GUILD_CHANGE_CURRENT_PAGEID= 'GUILD_CHANGE_CURRENT_PAGEID' //更新即将访问的规则页id
export const GUILD_CHANGE_CURRENT_FAIL_PARTERMTER = 'GUILD_CHANGE_CURRENT_FAIL_PARTERMTER'

//礼包中心
export const GUILD_CENTER_HOME_UPDATE= 'GUILD_CENTER_HOME_UPDATE' //更新首页信息
export const GUILD_CENTER_GIFT_SEARCH_LIST= 'GUILD_CENTER_GIFT_SEARCH_LIST' //更新搜索列表信息
// export const GUILD_CENTER_GIFT_MORE_LIST= 'GUILD_CENTER_GIFT_MORE_LIST' //更新更多礼包列表
export const GUILD_CENTER_GIFT_INFO= 'GUILD_CENTER_GIFT_INFO' //更新礼包详情页

export const GUILD_CENTER_ACTIVITY_LIST= 'GUILD_CENTER_ACTIVITY_LIST' //更新活动列表
export const GUILD_CENTER_GIFT_LIST= 'GUILD_CENTER_GIFT_LIST' //更新首页礼包列表
export const GUILD_CENTER_GID_LIST= 'GUILD_CENTER_GID_LIST' //更新游戏查礼包列表
export const GUILD_CENTER_GIFT_GUILD= 'GUILD_CENTER_GIFT_GUILD' //更新礼包查公会列表
export const GUILD_CENTER_NOTIFY= 'GUILD_CENTER_NOTIFY' //通知会长申请礼包
export const GUILD_CENTER_FETCH_TT_GIFT= 'GUILD_CENTER_FETCH_TT_GIFT' //领取TT礼包
export const GUILD_CENTER_PURCHASE= 'GUILD_CENTER_PURCHASE' //会长申请（购买）公会礼包
export const GUILD_CENTER_UPDATE_GIFT_INFO= 'GUILD_CENTER_UPDATE_GIFT_INFO' //更新礼包列表中单个礼包信息
export const GUILD_CENTER_UPDATE_LAST_RECORD= 'GUILD_CENTER_UPDATE_LAST_RECORD' //更新最后一条领取记录
export const GUILD_CENTER_CLEAR_LAST_RECORD= 'GUILD_CENTER_CLEAR_LAST_RECORD' //清空领取记录（礼包详情预加载礼包跟领取记录不同时）

//礼包中心 更新当前参数
export const CHANGE_CENTER_CURRENT_GIFT= 'CHANGE_CENTER_CURRENT_GIFT' //更新即将访问的礼包id
export const CHANGE_CENTER_CURRENT_GAME= 'CHANGE_CENTER_CURRENT_GAME' //更新即将访问的游戏id,
export const CHANGE_CENTER_CURRENT_GIFT_LIST= 'CHANGE_CENTER_CURRENT_GIFT_LIST' //更新即将访问的游戏id,
// export const CHANGE_CENTER_CURRENT_KEYWORDS= 'CHANGE_CENTER_CURRENT_KEYWORDS' //更新即将访问的关键词,用于搜索页列表
export const CHANGE_CENTER_CURRENT_GIFT_GUILD_LIST= 'CHANGE_CENTER_CURRENT_GIFT_GUILD_LIST' //更新礼包查公会，礼包id
export const CHANGE_CENTER_CURRENT_SEARCH_LIST= 'CHANGE_CENTER_CURRENT_SEARCH_LIST' //更新即将访问的关键词,用于搜索页列表
export const CHANGE_CENTER_CURRENT_GIFT_LIST_POSITION= 'CHANGE_CENTER_CURRENT_GIFT_LIST_POSITION' //更新礼包列表当前所在位置('home' 'search' 'game')
export const GUILD_CENTER_CLEAR_SEARCH_LIST= 'GUILD_CENTER_CLEAR_SEARCH_LIST' //清空搜索结果
// export const GUILD_CENTER_CHANGE_PAGE_NAME= 'GUILD_CENTER_CHANGE_PAGE_NAME' //设置当前页面page_name
export const GUILD_CENTER_UPDATE_GIFT_DETAIL= 'GUILD_CENTER_UPDATE_GIFT_DETAIL' //更新礼包详情

/*******合并部分***********/
//游戏专区
export const GAME_AREA_SET_STATE = 'GAME_AREA_SET_STATE' //读取缓存
export const GAME_AREA_UPDATE_STATE = 'GAME_AREA_UPDATE_PROFILE' //请求专区数据
export const GAME_AREA_UPDATE_CURRENT_STATE = 'GAME_AREA_UPDATE_CURRENT_STATE' //更新current game
export const GAME_AREA_UPDATE_DOWNLOAD_PROGRESS = 'GAME_AREA_UPDATE_DOWNLOAD_PROGRESS' //更新下载进度
export const GAME_AREA_UPDATE_FOCUS_STATE = 'GAME_AREA_UPDATE_FOCUS_STATE' //更新关注状态
// export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE' //更新user profile
export const USER_PROFILE_LOCATION = 'USER_PROFILE_LOCATION' //更新本地的user数据
export const ZONE_GAME_NOTICE = 'ZONE_GAME_NOTICE' //游戏公告
export const ZONE_GAME_SERVISE = 'ZONE_GAME_SERVISE' //游戏开服
export const GAME_AREA_CURRENT_INFO = 'GAME_AREA_CURRENT_INFO' //当前专区的信息数据

//游戏福利预约
export const GAME_ORDER_UPDATE_STATE = 'GAME_ORDER_UPDATE_STATE' //初始化福利活动列表
